BEGIN;
SET TRANSACTION ISOLATION LEVEL REPEATABLE READ;
-- SESSION 1
BEGIN;
SET TRANSACTION ISOLATION LEVEL REPEATABLE READ;
-- SESSION 2
SELECT SUM(rating) FROM pizzeria;
-- SESSION 1
INSERT INTO pizzeria (id, name, rating) VALUES (11, 'Kazan Pizza 2', 4);
-- SESSION 2
COMMIT;
-- SESSION 2
SELECT SUM(rating) FROM pizzeria;
-- SESSION 1
COMMIT;
-- SESSION 1
SELECT SUM(rating) FROM pizzeria;
-- SESSION 1
SELECT SUM(rating) FROM pizzeria;
-- SESSION 2